### ISSUE TITLE
[ (CoroutineExceptionHandler.kt:111)#handleException ] okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by kxbyte** [LetMeOff/SimpleDownload#1]
https会出现这个情况
[ (CoroutineExceptionHandler.kt:111)#handleException ] okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR
加这个也没效果
.protocols(Collections.singletonList(Protocol.HTTP_1_1))
改成http正常的

**Comment by LetMeOff** [comment]
将DownloadConfig中的httpClientFactory重写一下试试，用你自己的OkHttpClient对象
